### ISSUE TITLE
Release manager for image-tools

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/image-tools#110]
@vbatts volunteered to be a release manager here but I believe @xiekeyang is also interested and there may be others.

@vbatts want to help out @xiekeyang with the process? I know some of it's documented here:
https://github.com/opencontainers/image-tools/blob/master/RELEASES.md#planning-a-release

**Comment by vbatts** [comment]
awesome!

**Comment by xiekeyang** [comment]
@caniszczyk @vbatts I'm glad to take responsible for releasing work. I have no experience before. So I'm appreciated for @vbatts help.

**Comment by xiekeyang** [comment]
@cyphar thanks for releasing 0.1.0 package. It had better to paste the vote link on release note. 
Another question, I take notice that for OCI tools like runtime-tools and runc, there is not integrity and signature verification. You add signature verification to image-tools. Maybe it is necessary of integrity verification, but if necessary of signature verification?

@opencontainers/image-tools-maintainers How to determine the interval of new version release? Refer to image-spec, I think we can release the new one after some big feature or many(10~20) patch merged, not to be limited by time(every 2 or 3 weeks). Do you agree?

**Comment by xiekeyang** [comment]
vote result link: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/niFeAfPy4uE

**Comment by cyphar** [comment]
@xiekeyang For `runc` I've always signed tags and signed binaries when I did a release. I know that other maintainers haven't done it in the past, but that's not a good idea IMO. @vbatts similarly always signs tags. I was trying to get requirements about signed tags and releases into `CONTRIBUTING.md` last year but we decided to punt on it and leave it up to the maintainers.

As for the cadence of releases, time-based releases aren't a bad idea while we're still pre-1.0.

**Comment by vbatts** [comment]
Closing this, as someone (that isn't me) has done one release!

@xiekeyang if you have feedback on the process, that can be PRs to the release process, please open them. :100:

**Comment by xiekeyang** [comment]
@opencontainers/image-tools-maintainers As only 3 PRs (no big features) were merged after v0.1.0, I want to postpone release vote at least one week, is it OK?

@cyphar Could you please present a manual of gpgsign for released packae here or where I can access, I would arrange and paste them to RELEASE.md. Thanks so much!

**Comment by xiekeyang** [comment]
postpone release vote of v0.2.0

**Comment by cyphar** [comment]
I consider the weekly release cadence to be a guideline (runC definitely hasn't followed it, and neither has runtime-tools). The release rules are more important for specs than for the tool repos. I'll write up how to sign everything later today.

**Comment by wking** [comment]
On Wed, Mar 15, 2017 at 02:38:41AM -0700, Aleksa Sarai wrote:
> I consider the weekly release cadence to be a guideline (runC
> definitely hasn't followed it, and neither has runtime-tools).

The only OCI release timeline policy I can find is for specs (so
*-spec, but not runC or *-tools), and that recommends a monthly
cadence [1].  There is (for specs) a one week minimum, but that's
mostly because a new release can only be proposed after its parent has
landed [2] and votes should cook for a week to collect feedback [3].

So I don't think there's a weekly cadence recommendation to worry
about ;).  Cutting monthly releases, or just waiting for sufficient
changes to build up in master, sounds good to me.

[1]: https://github.com/opencontainers/project-template/blob/16f84db17e49bcafbef9209a8e90185b7df7f884/RELEASES.md#timelines
[2]: https://github.com/opencontainers/project-template/blob/16f84db17e49bcafbef9209a8e90185b7df7f884/RELEASES.md#parallel-releases
[3]: https://github.com/opencontainers/project-template/blob/16f84db17e49bcafbef9209a8e90185b7df7f884/GOVERNANCE.md#voting

**Comment by cyphar** [comment]
@xiekeyang Here is the document. https://gist.github.com/cyphar/21a1b213901a0a0ec19764ac03646ebe
