### ISSUE TITLE
vendor golang.org/x/sys seems large

### ISSUE THREAD

**Issue by xiekeyang** [opencontainers/image-tools#159]
@opencontainers/image-tools-maintainers vendor `golang.org/x/sys` seems to be ~~redundant~~ large. ~~But it exists in~~ And managed by [glide.lock](https://github.com/opencontainers/image-tools/blob/master/glide.lock#L32).
We might be able to remove the package code totally. That is big up to 4MB.
And, I think we can remove glide files from this repo. Commiter can add vendor codes manually. While I know this idea strengths and weaknesses.

**Comment by cyphar** [comment]
Absolutely not. Removing `vendor` from the repo means that you can no longer build code reproducibly, nor can they be certain what code was used to build our binaries. If `golang.org/x/sys` breaks in the future (unlikely but the point stands) then users will have to guess what version of the code worked. Distributions no longer can actually be sure what code needs to be used to build the project.

While 4MB is fairly large, the reason why it's so large is because `glide` does not remove unused dependencies. I would prefer moving to https://github.com/lk4d4/vndr (which does clean dependencies and will reduce the size of `vendor/` significantly) over removing *very important* information.

**Comment by xiekeyang** [comment]
My fault. it is used in https://github.com/opencontainers/image-tools/blob/master/vendor/github.com/Sirupsen/logrus/terminal_solaris.go
If under solaris terminal, it will not work.

**Comment by stevvooe** [comment]
What exactly is the proposal here?

**Comment by xiekeyang** [comment]
@stevvooe I will try the proposal from @cyphar , to debug by  https://github.com/lk4d4/vndr to reduce vendor size.

**Comment by stevvooe** [comment]
@xiekeyang Who cares about the size? It really doesn't matter. This is a waste of effort.

**Comment by xiekeyang** [comment]
Close it temporarily
