### ISSUE TITLE
pull requests pending

### ISSUE THREAD

**Issue by xiekeyang** [opencontainers/image-tools#34]
@opencontainers/image-spec-maintainers 
The pull requests seems to have been pending a few days. If you are planing to merge them, or there are some problem on processing?
Thanks.

**Comment by wking** [comment]
On Wed, Oct 05, 2016 at 08:59:10PM -0700, xiekeyang wrote:
> The pull requests seems to have been pending a few days. If you are
> planing to merge them, or there are some problem on processing?

In yesterday's ContainerCon Europe [1], @vbatts mentioned this and my
recollection was that the issue was a combination of low maintainer
bandwidth and high comment volume.  I expect non-maintainer input here
will quiet down as the backlog builds, and then the maintainers will
be able to dig back out from under the pile ;).

[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/BHYX5lv5h3E

**Comment by vbatts** [comment]
@xiekeyang I fully hear your frustration. This process is needing improvement. And likewise for your frustration of getting formidable review from maintainers of the project, it is difficult with there is a rough ratio of signal to noise.
I personally do what I can to give direct review regardless of the noise that happens.

**Comment by xiekeyang** [comment]
@vbatts 
Appreciate! Actually it is pleasure to make deep communication with maintainers. And I would do my best to make contribution.
